config/routes.rb
Myapp::Application.routes.draw do

  resources :topicos_conteudos

  resources :formato_conteudos

  resources :canais do
    collection do
      match "ver_conteudos_canal", via: [:get, :post]
    end
  end

  resources :salvar_tags do
    collection do
      match "salva_tag", via: [:get, :post]
    end
  end

  resources :pre_login do
    collection do
      match "index", via: [:get, :post]
    end
  end
  resources :meus_cursos do
    collection do
      match "visualizar_curso", via: [:get, :post]
    end
  end
  resources :carrinhos do
    collection do
      match "pagamento", via: [:get, :post]
      match "add_carrinho", via: [:get, :post]
      match "deleta_item", via: [:get, :post] 
      match "finaliza_compra", via: [:get, :post]
    end
  end
  resources :minha_lista do
    collection do
      match "add_lista", via: [:get, :post]
      match "deleta_lista", via: [:get, :post]
    end
  end

  resources :autor_conteudo_conteudos
  resources :conteudos
  resources :autor_conteudos
  resources :conteudo_tipos
  resources :empresarial_ramos
  resources :orientacoes_empresas
  resources :orientacoes_desafios
  resources :desafios_empresas do
    collection do
      match 'todos_desafios', via: [:get, :post]
    end
  end
  resources :metodologia_desafios
  resources :status_desafios
  resources :dilemas
  resources :areas_conhecimentos
  resources :empresas_pessoas
  resources :empresas
  resources :modulos_pessoas do
    collection do
      match 'escolher_modulo', via: [:get, :post]
      match 'setar_modulo', via: [:get, :post]
    end
  end
  resources :modulos
  resources :pessoas
  devise_for :usuarios
  # You can have the root of your site routed with "root"
  root to: 'pages#index'

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"
  get "dashboards/home"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"
  get "pages/escolher_empresa"
  get "pages/escolher_modulo"
  get "pages/escolher_funcao"
  get "pages/index"
  get "pages/visualizar_curso"
  get "pages/landing_gerador"
  get "pages/painel_gerador"
  match "pages/assistir_curso", via: [:get, :post]
  match "pages/curso", via: [:get, :post]
  match "pages/modulo_gerador", via: [:get, :post]
  match "pages/painel", via: [:get, :post]
  match "pages/conteudos_canal", via: [:get, :post]
  match "pages/topicos_conteudo", via: [:get, :post]
  match "pages/topico_conteudo", via: [:get, :post]
  match "pages/show_topico", via: [:get, :post]
  match "pages/show_topicos", via: [:get, :post]
  match "pages/busca_conteudo", via: [:get, :post]
  match "pages/conteudo_busca", via: [:get, :post]
  match "pages/conteudo_error", via: [:get, :post]

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

app/models/carrinho.rb
class Carrinho < ActiveRecord::Base
  belongs_to :conteudo_tipo
  belongs_to :autor_conteudo
end

app/controllers/carrinhos_controller.rb
class CarrinhosController < ApplicationController
  before_action :set_carrinho, only: [:show, :edit, :update, :destroy]

  # GET /carrinhos
  # GET /carrinhos.json
  def index
    @itens_carrinhos = ItensCarrinho.joins(:carrinho).where("carrinhos.pessoa_id = ? AND carrinhos.ativo = ? AND itens_carrinhos.ativo = ?", current_usuario.id, true, true)

  end

  # GET /carrinhos/1
  # GET /carrinhos/1.json
  def show
  end

  # GET /carrinhos/new
  def new
    @carrinho = Carrinho.new
    #@product = ItensCarrinho.find(params[:product_id])
    #@session_id = (PagSeguro::Session.create).id
  end
  def add_carrinho
    if !Carrinho.where(ativo: true, pessoa_id: Pessoa.find_by(usuario_id: current_usuario.id, ativo: true).id).blank?
      if ItensCarrinho.where(conteudo_id: params[:conteudo_id], ativo: true).blank?
        @conteudo = Conteudo.find_by(id: params[:conteudo_id], ativo: true)
        @itens_carrinho = ItensCarrinho.new
        @itens_carrinho.nome = @conteudo.nome
        
        @itens_carrinho.preco_sugerido = @conteudo.preco_sugerido
        @itens_carrinho.conteudo_id = params[:conteudo_id]
        @itens_carrinho.carrinho_id = Carrinho.where(ativo: true, pessoa_id: Pessoa.find_by(usuario_id: current_usuario.id, ativo: true).id).last.id
        @itens_carrinho.save
        @notice_carrinho = true
        @notice = "Item adicionado ao carrinho!"
        @busca_carrinho = ItensCarrinho.where(ativo: true)
        render :inline => render_to_string(:partial => 'botao_carrinho')

      else
        @busca_carrinho = ItensCarrinho.where(ativo: true)
        @notice_pass_carrinho = true
        @notice = "Item já existente no carrinho!"
        render :inline => render_to_string(:partial => 'botao_carrinho')
      end  
      
    else
      @carrinhos = Carrinho.new
      @carrinhos.pessoa_id = Pessoa.find_by(usuario_id: current_usuario.id, ativo: true).id
      if @carrinhos.save
        if ItensCarrinho.where(conteudo_id: params[:conteudo_id]).blank?
          @conteudo = Conteudo.find_by(id: params[:conteudo_id], ativo: true)
          @itens_carrinho = ItensCarrinho.new
          @itens_carrinho.nome = @conteudo.nome
          
          @itens_carrinho.preco_sugerido = @conteudo.preco_sugerido
          @itens_carrinho.conteudo_id = params[:conteudo_id]
          @itens_carrinho.carrinho_id = Carrinho.where(ativo: true, pessoa_id: Pessoa.find_by(usuario_id: current_usuario.id, ativo: true).id).last.id
          @itens_carrinho.save
          @notice_pass_carrinho = true
          @notice = "Item adicionado ao carrinho"
          @busca_carrinho = ItensCarrinho.where(ativo: true)
          render :inline => render_to_string(:partial => 'botao_carrinho')

        else
          @busca_carrinho = ItensCarrinho.where(ativo: true)
          @notice_pass_carrinho = true
          @notice = "Item já existente no carrinho"
          render :inline => render_to_string(:partial => 'botao_carrinho')
        end  
      end
    end

  end

  def deleta_item
    @itens_carrinhos = ItensCarrinho.joins(:carrinho).where("carrinhos.pessoa_id = ? AND carrinhos.ativo = ? AND itens_carrinhos.ativo = ?", current_usuario.id, true, true)
    if @itens_carrinho = ItensCarrinho.find_by(id: params[:itens_carrinho_id], ativo: true)   
      @itens_carrinho.ativo = false
      @itens_carrinho.save

    end
    render :inline => render_to_string(:partial => 'carrinho.html.erb')
      #render '_carrinho.html.erb'
  end

  def finaliza_compra
    pessoa = Pessoa.find_by(usuario_id: current_usuario.id, ativo: true)
    carrinho = Carrinho.find_by(pessoa_id: pessoa.id, ativo: true)

    ItensCarrinho.where(ativo: true, carrinho_id: carrinho.id).each do |item_carrinho|
      meu_curso = MeusCurso.new
      meu_curso.conteudo_id = item_carrinho.conteudo_id
      meu_curso.pessoa_id = pessoa.id
      meu_curso.save
    end

    carrinho.update(concluido: true)

    redirect_to meus_cursos_path
  end

  # GET /carrinhos/1/edit
  def edit
  end

  # POST /carrinhos
  # POST /carrinhos.json
  def pagamento
    render pagamento_carrinhos_path
  end

  def create
    raise "qualquer coisa".inspect
    @carrinho = Carrinho.new(carrinho_params)

    @product = Product.find(params[:product_id])
 
    payment = PagSeguro::CreditCardTransactionRequest.new
    payment.notification_url = "https://secret-wave-53573.herokuapp.com/notification  "
    payment.payment_mode = "gateway"
 
    # Aqui vão os itens que serão cobrados na transação, caso você tenha multiplos itens
    # em um carrinho altere aqui para incluir sua lista de itens
    payment.items << { id: @product.id, description: @product.description, amount: @product.price, weight: 0 } # Criando uma referencia para a nossa ORDER reference = "REF_#{(0...8).map { (65 + rand(26)).chr }.join}_#{@product.id}" payment.reference = reference payment.sender = { hash: params[:sender_hash], name: params[:name], email: params[:email] } payment.credit_card_token = params[:card_token] payment.holder = { name: params[:card_name], birth_date: params[:birthday], document: { type: "CPF", value: params[:cpf] }, phone: { area_code: params[:phone_code], number: params[:phone_number] } } payment.installment = { value: @product.price, quantity: 1 } puts "=> REQUEST"
    puts PagSeguro::TransactionRequest::RequestSerializer.new(payment).to_params
    puts
 
    payment.create
 
    # Cria uma Order para registro das transações
    Order.create(product_id: @product.id, buyer_name: params[:name], reference: reference, status: 'pending')
 
    if payment.errors.any?
     puts "=> ERRORS"
     puts payment.errors.join("\n")
     render plain: "Erro No Pagamento #{payment.errors.join("\n")}"
    else
     puts "=> Transaction"
     puts "  code: #{payment.code}"
     puts "  reference: #{payment.reference}"
     puts "  type: #{payment.type_id}"
     puts "  payment link: #{payment.payment_link}"
     puts "  status: #{payment.status}"
     puts "  payment method type: #{payment.payment_method}"
     puts "  created at: #{payment.created_at}"
     puts "  updated at: #{payment.updated_at}"
     puts "  gross amount: #{payment.gross_amount.to_f}"
     puts "  discount amount: #{payment.discount_amount.to_f}"
     puts "  net amount: #{payment.net_amount.to_f}"
     puts "  extra amount: #{payment.extra_amount.to_f}"
     puts "  installment count: #{payment.installment_count}"
 
     puts "    => Items"
     puts "      items count: #{payment.items.size}"
     payment.items.each do |item|
       puts "      item id: #{item.id}"
       puts "      description: #{item.description}"
       puts "      quantity: #{item.quantity}"
       puts "      amount: #{item.amount.to_f}"
     end
 
     puts "    => Sender"
     puts "      name: #{payment.sender.name}"
     puts "      email: #{payment.sender.email}"
     puts "      phone: (#{payment.sender.phone.area_code}) #{payment.sender.phone.number}"
     puts "      document: #{payment.sender.document}: #{payment.sender.document}"
     render plain: "Sucesso, seu pagamento será processado :)"
    end

    respond_to do |format|
      if @carrinho.save
        format.html { redirect_to @carrinho, notice: 'Item do carrinho cadastrado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @carrinho }
      else
        format.html { render action: 'new' }
        format.json { render json: @carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carrinhos/1
  # PATCH/PUT /carrinhos/1.json
  def update
    respond_to do |format|
      if @carrinho.update(carrinho_params)
        format.html { redirect_to @carrinho, notice: 'Item do carrinho alterado com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carrinhos/1
  # DELETE /carrinhos/1.json
  def destroy
    @carrinho.update(ativo: false)
    respond_to do |format|
      format.html { redirect_to carrinhos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrinho
      @carrinho = Carrinho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrinho_params
      params.require(:carrinho).permit(:nome, :autor_conteudo_id, :preco_sugerido, :conteudo_id, :pessoa_id, :ativo)
    end
end

app/helpers/carrinhos_helper.rb
module CarrinhosHelper
end

app/views/carrinhos/_botao_carrinho.html.erb
<script type="text/javascript">
	$(document).ready(function(){
    <% if @notice_pass_carrinho == true %>
    	//$('#modal-add-carrinho').modal('show');
        swal({
          title: "<%= @notice %>",
          type: "warning",
          closeOnClickOutside: true,
          timer: 3000,
          confirmButtonColor: "#222",
          confirmButtonText: "OK",
          closeOnConfirm: true
        });
		<% end %>
    <% if @notice_carrinho == true %>
        swal({
          title: "<%= @notice %>",
          type: "success",
          closeOnClickOutside: true,
          timer: 3000,
          confirmButtonColor: "#222",
          confirmButtonText: "OK",
          closeOnConfirm: true
        });
    <% end %>
	});
</script>


<!-- <a href="<%= carrinhos_path %>" class= "a">
  <div>
      <button class="btn btn-circle btn-lg" type="button" title="Carrinho de compras" style="margin-top: 10px;">
        <i class="fa fa-shopping-cart" style="font-size:28px; margin-left: -5px;"></i>
      </button>
  	<#% if !@busca_carrinho.blank? %>
  		<span class="badge badge-warning pull-right">
  			<%= @busca_carrinho.count %>
  		</span>
  	<#% end %>
  </div>
</a> -->
<a href="<%= carrinhos_path %>" title="Carrinho" class= "a">
  <% if !@busca_carrinho.blank? %>
    <span class="badge badge-primary pull-right" style="margin-left: -15px;z-index: 60"><%= @busca_carrinho.count %></span>
  <% end %>
  <button class="btn btn-outline" type="button" title="Carrinho de compras"><i class="fa fa-shopping-cart" style="font-size:22px; margin-top: -3px; margin-left: 3px;display: block;"></i></button>
</a>
<div class="modal fade" id="modal-add-carrinho" style="z-index: 3000 !important;">
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <center><h3><%= @notice %></h3></center>
      </div>
  	</div>
  </div>
</div>
<style type="text/css">
  #.modal-backdrop {
    !z-index: 2040 !important;
  }

</style>

app/views/carrinhos/_form.html.erb
<%= form_for(@carrinho) do |f| %>
  <% if @carrinho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carrinho.errors.count, "error") %> prohibited this carrinho from being saved:</h2>
      <ul>
      <% @carrinho.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conteudo_tipo_id %><br>
    <%= f.text_field :conteudo_tipo_id %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :autor_conteudo_id %><br>
    <%= f.text_field :autor_conteudo_id %>
  </div>
  <div class="field">
    <%= f.label :preco_sugerido %><br>
    <%= f.text_field :preco_sugerido %>
  </div>
  <div class="field">
    <%= f.label :ativo %><br>
    <%= f.check_box :ativo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carrinhos/edit.html.erb
<h1>Editing Carrinho</h1>

<%= render 'form' %>

<%= link_to 'Show', @carrinho %> |
<%= link_to 'Back', carrinhos_path %>

app/views/carrinhos/index.html.erb
<div id="carrinho_partial">
  <!-- <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
      <h2>Carrinho de compras</h2>
        <ol class="breadcrumb">
          <li>
            <a href="<%#= pages_index_path %>" style = "font-size: 15px;" title="home"><i class="fa fa-home" aria-hidden="true"></i></a>
          </li>
          <li class="active">
            <strong>Carrinho</strong>
          </li>
        </ol>
      </div>
      <div class="col-lg-2">

      </div>
  </div> -->
  <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">

      <% if @itens_carrinhos.count == 0 %>
        <div class="col-lg-12">
          <div class="middle-box text-center animated fadeInRightBig">
            <i class="fa fa-shopping-cart" style="font-size: 200px; color: #e8e9eb;"></i>
              <h3 class="font-bold">Seu carrinho está vazio :( </h3>
              <div class="error-desc">
                Continue acessando a plataforma para encontrar um conteúdo!<br>
                <br><%= link_to 'Continuar comprando'.html_safe, pages_index_path, :class => 'btn btn-primary', :style => 'font-size: 17px;'%>
              </div>
          </div>
        </div>
      <% else %>
        <div class="col-md-9">
            <div class="ibox">
              <div class="ibox-title">
                <span class="pull-right">(<strong><%= @itens_carrinhos.count %></strong>) itens</span>
                <h5>Itens no seu carrinho </h5>
              </div>
              <div class="ibox-content">
                <div class="table-responsive">
                  <table class="table shoping-cart-table">
                    <tbody>
                      <% @valor_total_carrinho = 0 %>
                      <% @itens_carrinhos.each do |itens_carrinho| %>
                        <tr>
                          <td width="200">
                            <img src="<%= itens_carrinho.conteudo.image %>" style="width:200px; height: auto;">
                          </td>
                          <td class="desc">
                            <h3>
                              <a href="#" class="text-navy">
                                <%= itens_carrinho.nome %>
                              </a>
                            </h3>
                                <!--<ul>
                                <#% AutorConteudoConteudo.where(conteudo_id: itens_carrinho.conteudo_id).each do |autor_conteudo_conteudo| %>
                                  <#% AutorConteudo.where(id: autor_conteudo_conteudo.autor_conteudo_id).each do |autor_conteudo| %>
                                    <li><#%= autor_conteudo.nome%></li>
                                  <#% end %>
                                <#% end %> 
                                </ul> -->
                            <!-- <dl class="small m-b-none">
                              <dt>Autor(es) do conteúdo:</dt>
                                <%# @autor = AutorConteudoConteudo.where(conteudo_id: itens_carrinho.conteudo_id) %>
                                <%# @autor.each do |autor| %>
                                  <ul style="list-style-type: none;">
                                    <li><%#= autor.autor_conteudo_id.blank? ? "" : Pessoa.find_by(usuario_id: current_usuario.id).nome %></li>
                                  </ul>
                                <%#end%>
                            </dl> -->
                            <div class="m-t-sm">
                              <!-- <a href="#" class="text-muted"><i class="fa fa-gift"></i> Add gift package</a>
                                          | -->
                              <!-- <button class="text-muted" id="deleta_item-<%#= itens_carrinho.id %>" ><i class="fa fa-trash"></i> Remover item</button> -->
                              <a href="" class="a" id="deleta_item-<%= itens_carrinho.id %>"><i class="fa fa-trash"></i> Remover item</a>
                            </div>
                          </td>
                          <td>
                            <h4>
                              <% @valor_total_carrinho = @valor_total_carrinho.to_d + itens_carrinho.preco_sugerido.to_d %>
                               <%= number_to_currency(itens_carrinho.preco_sugerido.to_d, unit: "R$ ", separator: ",", delimiter: ".", precision: 2) %>
                            </h4>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="ibox-content">
                <%= link_to(finaliza_compra_carrinhos_path, :class => 'btn btn-primary pull-right', :title => 'Finalizar compra', :style => 'min-width: 100px;') do %>
                  <i class="fa fa-shopping-cart"></i> Finalizar compra
                <%end%>
                 <%= link_to '<i class="fa fa-arrow-left"></i> Continuar comprando'.html_safe, pages_index_path, :class => 'btn btn-white'%>
                  <!--  <div class="row"> -->
                  <!-- <div class="col-lg-9">
                  <%#= link_to '<i class="fa fa-arrow-left"></i> Continuar comprando'.html_safe, pages_index_path, :class => 'btn btn-white'%>
                  </div> -->
                  <!-- <div class= "col-lg-3"> -->
                    <!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
                      <!-- <form action="https://pagseguro.uol.com.br/checkout/v2/cart.html?action=add" method="post" onsubmit="PagSeguroLightbox(this); return false;"> -->
                      <!-- NÃO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
                      <!-- <input type="hidden" name="itemCode" value="57E7BE11A3A3ADEAA4EFFFB7A3C1F96B" />
                      <input type="hidden" name="iot" value="button" />
                      <input type="image" src="https://stc.pagseguro.uol.com.br/public/img/botoes/pagamentos/205x30-comprar-preto.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
                      </form>
                      <script type="text/javascript" src="https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.lightbox.js"></script> -->
                    <!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
                  <!-- </div> -->
                <!-- </div> -->
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="ibox">
              <div class="ibox-title">
                <h5>Total</h5>
              </div>
              <div class="ibox-content">
                <h2 class="font-bold">
                  <!-- R$ <%#= @valor_total_carrinho%> -->
                  <!-- R<%#= number_to_currency(@valor_total_carrinho) %> -->
                  <%= number_to_currency(@valor_total_carrinho, unit: "R$ ", separator: ",", delimiter: ".", precision: 2) %>
                </h2>
                <hr/>
                <div class="m-t-sm">
                  <!-- <div class="btn-group"> -->
                      <!-- <a href="#" class="btn btn-primary btn-sm" style="min-width: 116px;"><i class="fa fa-shopping-cart"></i> Finalizar</a> -->
                      <%= link_to(finaliza_compra_carrinhos_path, :class => 'btn btn-primary btn-sm', :title => 'Finalizar compra', :style => 'min-width: 100px;') do %>
                        <i class="fa fa-shopping-cart"></i> Finalizar
                      <%end%>
                      <a href="#" class="btn btn-white btn-sm"> Cancelar compra</a>

                  <!-- </div> -->
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
<style type="text/css">
  .a{
    color: black;
  }
  .a:hover{
    color: #676a6c;
  }
</style>
  <script type="text/javascript">
    $(document).ready(function(){
      <% @itens_carrinhos.each do |itens_carrinho| %>   
        $("#deleta_item-<%= itens_carrinho.id %>").click(function(e){
            e.preventDefault();
            $.ajax({
              method: 'GET',
              url: '/carrinhos/deleta_item',
              data: {itens_carrinho_id: <%= itens_carrinho.id %>}

            })
            .done(function(retorno){
              $("#carrinho_partial").html(retorno);
            });
        });
      <% end %>
    });
  </script>

app/views/carrinhos/new.html.erb
<h1>New Carrinho</h1>

<%= render 'form' %>

<%= link_to 'Back', carrinhos_path %>

app/views/carrinhos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conteudo tipo:</strong>
  <%= @carrinho.conteudo_tipo %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @carrinho.nome %>
</p>

<p>
  <strong>Autor conteudo:</strong>
  <%= @carrinho.autor_conteudo %>
</p>

<p>
  <strong>Preco sugerido:</strong>
  <%= @carrinho.preco_sugerido %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @carrinho.ativo %>
</p>

<%= link_to 'Edit', edit_carrinho_path(@carrinho) %> |
<%= link_to 'Back', carrinhos_path %>