config/routes.rb
Myapp::Application.routes.draw do

  resources :topicos_conteudos

  resources :formato_conteudos

  resources :canais do
    collection do
      match "ver_conteudos_canal", via: [:get, :post]
    end
  end

  resources :salvar_tags do
    collection do
      match "salva_tag", via: [:get, :post]
    end
  end

  resources :pre_login do
    collection do
      match "index", via: [:get, :post]
    end
  end
  resources :meus_cursos do
    collection do
      match "visualizar_curso", via: [:get, :post]
    end
  end
  resources :carrinhos do
    collection do
      match "pagamento", via: [:get, :post]
      match "add_carrinho", via: [:get, :post]
      match "deleta_item", via: [:get, :post] 
      match "finaliza_compra", via: [:get, :post]
    end
  end
  resources :minha_lista do
    collection do
      match "add_lista", via: [:get, :post]
      match "deleta_lista", via: [:get, :post]
    end
  end

  resources :autor_conteudo_conteudos
  resources :conteudos
  resources :autor_conteudos
  resources :conteudo_tipos
  resources :empresarial_ramos
  resources :orientacoes_empresas
  resources :orientacoes_desafios
  resources :desafios_empresas do
    collection do
      match 'todos_desafios', via: [:get, :post]
    end
  end
  resources :metodologia_desafios
  resources :status_desafios
  resources :dilemas
  resources :areas_conhecimentos
  resources :empresas_pessoas
  resources :empresas
  resources :modulos_pessoas do
    collection do
      match 'escolher_modulo', via: [:get, :post]
      match 'setar_modulo', via: [:get, :post]
    end
  end
  resources :modulos
  resources :pessoas
  devise_for :usuarios
  # You can have the root of your site routed with "root"
  root to: 'pages#index'

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"
  get "dashboards/home"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"
  get "pages/escolher_empresa"
  get "pages/escolher_modulo"
  get "pages/escolher_funcao"
  get "pages/index"
  get "pages/visualizar_curso"
  get "pages/landing_gerador"
  get "pages/painel_gerador"
  match "pages/assistir_curso", via: [:get, :post]
  match "pages/curso", via: [:get, :post]
  match "pages/modulo_gerador", via: [:get, :post]
  match "pages/painel", via: [:get, :post]
  match "pages/conteudos_canal", via: [:get, :post]
  match "pages/topicos_conteudo", via: [:get, :post]
  match "pages/topico_conteudo", via: [:get, :post]
  match "pages/show_topico", via: [:get, :post]
  match "pages/show_topicos", via: [:get, :post]
  match "pages/busca_conteudo", via: [:get, :post]
  match "pages/conteudo_busca", via: [:get, :post]
  match "pages/conteudo_error", via: [:get, :post]

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

app/models/metodologia_desafio.rb
class MetodologiaDesafio < ActiveRecord::Base
end

app/controllers/metodologia_desafios_controller.rb
class MetodologiaDesafiosController < ApplicationController
  before_action :set_metodologia_desafio, only: [:show, :edit, :update, :destroy]

  # GET /metodologia_desafios
  # GET /metodologia_desafios.json
  def index
    @metodologia_desafios = MetodologiaDesafio.where(ativo: true)
  end

  # GET /metodologia_desafios/1
  # GET /metodologia_desafios/1.json
  def show
  end

  # GET /metodologia_desafios/new
  def new
    @metodologia_desafio = MetodologiaDesafio.new
  end

  # GET /metodologia_desafios/1/edit
  def edit
  end

  # POST /metodologia_desafios
  # POST /metodologia_desafios.json
  def create
    @metodologia_desafio = MetodologiaDesafio.new(metodologia_desafio_params)

    respond_to do |format|
      if @metodologia_desafio.save
        format.html { redirect_to @metodologia_desafio, notice: 'Metodologia cadastrada com sucesso.' }
        format.json { render action: 'show', status: :created, location: @metodologia_desafio }
      else
        format.html { render action: 'new' }
        format.json { render json: @metodologia_desafio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metodologia_desafios/1
  # PATCH/PUT /metodologia_desafios/1.json
  def update
    respond_to do |format|
      if @metodologia_desafio.update(metodologia_desafio_params)
        format.html { redirect_to @metodologia_desafio, notice: 'Metodologia alterada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @metodologia_desafio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metodologia_desafios/1
  # DELETE /metodologia_desafios/1.json
  def destroy
    @metodologia_desafio.update(ativo: false)
    respond_to do |format|
      format.html { redirect_to metodologia_desafios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metodologia_desafio
      @metodologia_desafio = MetodologiaDesafio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metodologia_desafio_params
      params.require(:metodologia_desafio).permit(:nome, :ativo)
    end
end

app/helpers/metodologia_desafios_helper.rb
module MetodologiaDesafiosHelper
end

app/views/metodologia_desafios/_form.html.erb
<%= form_for(@metodologia_desafio) do |f| %>
  <% if @metodologia_desafio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metodologia_desafio.errors.count, "error") %> prohibited this metodologia_desafio from being saved:</h2>

      <ul>
      <% @metodologia_desafio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-horizontal">
    <div class="form-group">
      <%= f.label :nome, "Nome:" %> <e style="color: black">*</e><br>
      <%= f.text_field :nome, class: "form-control", :required => true %>
    </div>
    <div class="actions ">
      <%= button_tag(type: 'submit', class: "btn btn-white ", title: 'Salvar') do %>
        <i class="fa fa-save"></i> Salvar
      <% end %>
    </div>
  </form>
<% end %>

app/views/metodologia_desafios/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title border-rsup">
					<div class="row">
						<div class="col-lg-1 col-sm-2 col-md-2 col-xs-2">
							<%= link_to '<i class="fa fa-reply"></i> Voltar'.html_safe,metodologia_desafios_path, :class => 'btn btn-white', :title => 'Voltar/Cancelar'%>
						</div>
						<div class="col-lg-11 col-sm-10 col-md-10 col-xs-10">
							<h2 align="center">Editando Metodologia</h2>	
						</div>
					</div>
				</div>
				<div class="ibox-content border-rinf">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/metodologia_desafios/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <div class="row">
            <div class="col-xs-2 col-sm-1 col-md-1 col-lg-1 ">
              <h4><%= link_to '<i class="fa fa-plus"></i> Novo'.html_safe, new_metodologia_desafio_path, :class => 'btn btn-white', :title => 'Novo Perfil de Acesso' %></h4>
            </div>
            <div class="col-xs-10 col-sm-11 col-md-11 col-lg-11 ">
              <div style="text-align:center">
                <h2>Metodologias <span class="badge badge-primary"><%= @metodologia_desafios.count %></span></h2>
              </div>
            </div>
          </div>
        </div>
        <p id="notice">
          <center class="alert-info">
            <%= notice %> 
          </center>
        </p>
        <% @metodologia_desafios.each do |metodologia_desafio| %>

        <div class="col-md-4">
          <div class="ibox-content">
            <div class="row">
              <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 ">
                <h2>
                  <%= metodologia_desafio.nome if !metodologia_desafio.nome.nil? %>
                </h2>
              </div>

              <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 ">
                <a class="dropdown-toggle btn btn-white" data-toggle="dropdown" href="#">
                  <i class="fa fa-wrench"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                  <li>
                    <%= link_to '<i class="fa fa-search"></i> Visualizar'.html_safe, metodologia_desafio, :title => 'Visualizar' %>
                  </li>
                  <li>
                    <%= link_to '<i class="fa fa-edit"></i> Editar'.html_safe, edit_metodologia_desafio_path(metodologia_desafio), :title => 'Editar' %>
                  </li>
                  <li>
                    <%= link_to '<i class="fa fa-trash"></i> Deletar'.html_safe, metodologia_desafio, method: :delete, data: { confirm: 'Tem certeza?' }, :title => 'Deletar' %>
                  </li>
                </ul>

              </div>
            </div>

          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/metodologia_desafios/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title border-rsup">
					<div class="row">
						<div class="col-lg-1 col-sm-2 col-md-2 col-xs-2">
							<%= link_to '<i class="fa fa-reply"></i> Voltar'.html_safe,metodologia_desafios_path, :class => 'btn btn-white', :title => 'Voltar/Cancelar' %>
						</div>
						<div class="col-lg-11 col-sm-10 col-md-10 col-xs-10">
							<h2 align="center">Nova Metodologia</h2> 
						</div>
					</div>
				</div>
				<div class="ibox-content border-rinf">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/metodologia_desafios/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title border-rsup">
          <div class="row">
            <div class="col-lg-1 col-sm-2 col-md-2 col-xs-2">
             <%= link_to '<i class="fa fa-reply"></i> Voltar'.html_safe, metodologia_desafios_path, :class => 'btn btn-white', :title => 'Voltar' %>
            </div>
            <div class="col-lg-11 col-sm-10 col-md-10 col-xs-10">
              <h2 align="center">Visualizando Metodologia</h2> 
            </div>
          </div>
        </div>
        <div class="ibox-content border-rinf">
          <p id="notice">
            <center class="alert-info">
              <%= notice %> 
            </center>
          </p>
          <div class="panel panel-default">
            <div class="panel-body">
              <p>
                <strong>Nome:</strong>
                <%= @metodologia_desafio.nome if !@metodologia_desafio.nome.nil? %>
              </p>
            </div>
          </div>
          <div>
            <%= link_to '<i class="fa fa-edit"></i> Editar'.html_safe, edit_metodologia_desafio_path(@metodologia_desafio), :class => 'btn btn-white  ', :title => 'Editar' %>
            <%= link_to '<i class="fa fa-plus"></i> Novo'.html_safe, new_metodologia_desafio_path, :class => 'btn btn-white', :title => 'Novo' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>