config/routes.rb
Myapp::Application.routes.draw do

  resources :topicos_conteudos

  resources :formato_conteudos

  resources :canais do
    collection do
      match "ver_conteudos_canal", via: [:get, :post]
    end
  end

  resources :salvar_tags do
    collection do
      match "salva_tag", via: [:get, :post]
    end
  end

  resources :pre_login do
    collection do
      match "index", via: [:get, :post]
    end
  end
  resources :meus_cursos do
    collection do
      match "visualizar_curso", via: [:get, :post]
    end
  end
  resources :carrinhos do
    collection do
      match "pagamento", via: [:get, :post]
      match "add_carrinho", via: [:get, :post]
      match "deleta_item", via: [:get, :post] 
      match "finaliza_compra", via: [:get, :post]
    end
  end
  resources :minha_lista do
    collection do
      match "add_lista", via: [:get, :post]
      match "deleta_lista", via: [:get, :post]
    end
  end

  resources :autor_conteudo_conteudos
  resources :conteudos
  resources :autor_conteudos
  resources :conteudo_tipos
  resources :empresarial_ramos
  resources :orientacoes_empresas
  resources :orientacoes_desafios
  resources :desafios_empresas do
    collection do
      match 'todos_desafios', via: [:get, :post]
    end
  end
  resources :metodologia_desafios
  resources :status_desafios
  resources :dilemas
  resources :areas_conhecimentos
  resources :empresas_pessoas
  resources :empresas
  resources :modulos_pessoas do
    collection do
      match 'escolher_modulo', via: [:get, :post]
      match 'setar_modulo', via: [:get, :post]
    end
  end
  resources :modulos
  resources :pessoas
  devise_for :usuarios
  # You can have the root of your site routed with "root"
  root to: 'pages#index'

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"
  get "dashboards/home"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"
  get "pages/escolher_empresa"
  get "pages/escolher_modulo"
  get "pages/escolher_funcao"
  get "pages/index"
  get "pages/visualizar_curso"
  get "pages/landing_gerador"
  get "pages/painel_gerador"
  match "pages/assistir_curso", via: [:get, :post]
  match "pages/curso", via: [:get, :post]
  match "pages/modulo_gerador", via: [:get, :post]
  match "pages/painel", via: [:get, :post]
  match "pages/conteudos_canal", via: [:get, :post]
  match "pages/topicos_conteudo", via: [:get, :post]
  match "pages/topico_conteudo", via: [:get, :post]
  match "pages/show_topico", via: [:get, :post]
  match "pages/show_topicos", via: [:get, :post]
  match "pages/busca_conteudo", via: [:get, :post]
  match "pages/conteudo_busca", via: [:get, :post]
  match "pages/conteudo_error", via: [:get, :post]

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

app/models/topicos_conteudo.rb
class TopicosConteudo < ActiveRecord::Base
  belongs_to :formato_conteudo

  #anexo de video
  #has_attached_file :video
  #validates_attachment :video, content_type: { content_type: ["video/mp4", "video/wmv"]}
  
  #has_attached_file :video,
  #:storage => :cloudinary,
  #:cloudinary_resource_type => :video

  #carrierwave video upload
  mount_uploader :video, VideoUploader 

  # after_save :add_tag

  # def add_tag 
  #   if self.video.present?  
  #     result = Cloudinary::Uploader.add_tag(model.conteudo_id, model.id, options = {resource_type: video})
  #   end
  # end 
end

app/controllers/topicos_conteudos_controller.rb
class TopicosConteudosController < ApplicationController
  before_action :set_topicos_conteudo, only: [:show, :edit, :update, :destroy]

  # GET /topicos_conteudos
  # GET /topicos_conteudos.json
  def index
    @topicos_conteudos = TopicosConteudo.where(ativo: true)
  end

  # GET /topicos_conteudos/1
  # GET /topicos_conteudos/1.json
  def show
  end

  # GET /topicos_conteudos/new
  def new
    @topicos_conteudo = TopicosConteudo.new
  end

  # GET /topicos_conteudos/1/edit
  def edit
  end

  # POST /topicos_conteudos
  # POST /topicos_conteudos.json
  def create
    @topico = TopicosConteudo.where(conteudo_id: params[:topicos_conteudo][:conteudo_id], ativo: true)
    @topicos_conteudo = TopicosConteudo.new(topicos_conteudo_params)
    #@topicos_conteudo.video = params[:topicos_conteudo][:video]

    respond_to do |format|
      if @topicos_conteudo.save
        # format.html do
        #   redirect_to salva_tag_salvar_tags_path(topicos_conteudo_id: @topicos_conteudo.id, conteudo_id:  @topicos_conteudo.conteudo_id)
        # end
        #result = Cloudinary::Uploader.rename(from_topicos_conteudo_id, to_topicos_conteudo_id, options = {})
        
        # format.html { redirect_to @topicos_conteudo, notice: 'Tópico do conteúdo cadastrado com sucesso.' }
        # format.json { render action: 'show', status: :created, location: @topicos_conteudo }
        format.html { redirect_to pages_topico_conteudo_path(conteudo_id: params[:topicos_conteudo][:conteudo_id], ativo: true) }
      else
        format.html { render action: 'new' }
        format.json { render json: @topicos_conteudo.errors, status: :unprocessable_entity }
      end
    end
  end

  def topicos_params
    params.require(:topicos_conteudo).permit(:video)
  end

  # PATCH/PUT /topicos_conteudos/1
  # PATCH/PUT /topicos_conteudos/1.json
  def update
    respond_to do |format|
      if @topicos_conteudo.update(topicos_conteudo_params)
        #@topicos_conteudo.video = params[:topicos_conteudo][:video]
        format.html { redirect_to @topicos_conteudo, notice: 'Tópico do conteúdo alterado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topicos_conteudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topicos_conteudos/1
  # DELETE /topicos_conteudos/1.json
  def destroy
    @topicos_conteudo.update(ativo: false)
    respond_to do |format|
      format.html { redirect_to topicos_conteudos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topicos_conteudo
      @topicos_conteudo = TopicosConteudo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topicos_conteudo_params
      params.require(:topicos_conteudo).permit(:descricao, :video, :link, :objetivo, :resumo, :conteudo_id, :formato_conteudo_id, :ativo)
    end
end

app/helpers/topicos_conteudos_helper.rb
module TopicosConteudosHelper
end

app/views/topicos_conteudos/_form.html.erb
<%= form_for(@topicos_conteudo) do |f| %>
  <% if @topicos_conteudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topicos_conteudo.errors.count, "error") %> prohibited this topicos_conteudo from being saved:</h2>

      <ul>
      <% @topicos_conteudo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-horizontal">
    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= f.label :conteudo_id, "Conteúdo:" %> <e style="color: black">*</e>
          <%= f.select :conteudo_id, Conteudo.where(ativo: true).collect {|u| [(u.nome if !u.nome.nil?), (u.id if !u.id.nil?)]}, {:prompt => 'Selecione o conteúdo'}, class: "form-control", :required => true  %>
        </div>
        <!-- <div class="form-group">
          <%#= f.label :formato_conteudo_id, "Formato de conteúdo:" %> <e style="color: black">*</e>
          <%#= f.select :formato_conteudo_id, FormatoConteudo.where(ativo: true).collect {|u| [(u.nome if !u.nome.nil?), (u.id if !u.id.nil?)]}, {:prompt => 'Selecione o formato de conteúdo'}, class: "form-control", :required => true  %>
        </div> -->
        <div class="form-group">
          <%= f.label :descricao, "Descrição do tópico de conteúdo:" %><e style="color: black">*</e><br>
          <%= f.text_area :descricao, class: "form-control", :required => true %>
        </div>
        <div class="form-group">
          <%= f.label :objetivo, "Objetivo" %><e style="color: black">*</e><br>
          <%= f.text_field :objetivo, class: "form-control", :required => true %>
        </div>
        <div class="form-group">
          <%= f.label :resumo, "Resumo do tópico de conteúdo:" %><e style="color: black">*</e><br>
          <%= f.text_area :resumo, class: "form-control", :required => true %>
        </div>
        <div class="form-group">
          <%= f.label :link, "Link do vídeo:" %><e style="color: black">*</e><br>
          <%= f.text_field :link, class: "form-control", :required => true %>
        </div>
        <!-- <div class="form-group">
          <%#= f.label :video, "Anexe o seu conteúdo" %><br>
          <%#= f.file_field :video%>
        </div> -->
    <div class="actions">
      <%= button_tag(type: 'submit', class: "btn btn-white ", title: 'Salvar') do %>
        <i class="fa fa-save"></i> Salvar
      <% end %>
      </div>
    </div>
    </div>
  </form>
<% end %>

app/views/topicos_conteudos/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title border-rsup">
					<div class="row">
						<div class="col-lg-1 col-sm-2 col-md-2 col-xs-2">
							<%= link_to '<i class="fa fa-reply"></i> Voltar'.html_safe,topicos_conteudos_path, :class => 'btn btn-white', :title => 'Voltar/Cancelar'%>
						</div>
						<div class="col-lg-11 col-sm-10 col-md-10 col-xs-10">
							<h2 align="center">Editando tópico de conteúdo</h2>	
						</div>
					</div>
				</div>
				<div class="ibox-content border-rinf">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/topicos_conteudos/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <div class="row">
            <div class="col-xs-2 col-sm-1 col-md-1 col-lg-1 ">
              <h4><%= link_to '<i class="fa fa-plus"></i> Novo'.html_safe, new_topicos_conteudo_path, :class => 'btn btn-white', :title => 'Novo tópico de conteúdo' %></h4>
            </div>
            <div class="col-xs-10 col-sm-11 col-md-11 col-lg-11 ">
              <div style="text-align:center">
                <h2>Tópicos de conteúdos</h2>
              </div>
            </div>
          </div>
        </div>
        <p id="notice">
          <center class="alert-info">
            <%= notice %> 
          </center>
        </p>
       <div class="table-responsive" style="padding-bottom: 130px;">
        <table class="table table-hover">
          <thead class="table table-bordered">
            <tr>
              <th>Conteúdo</th>
              <th>Descrição do tópico</th>
              <th>Objetivo</th>
              <th>Resumo</th>
              <!-- <th>Formato de conteúdo</th> -->
              <th>Link do vídeo</th>
              <th></th>
            </tr>
          </thead>
          <tbody class="table table-hover">
            <% @topicos_conteudos.each do |topicos_conteudo| %>
              <tr>
                <td><%= topicos_conteudo.conteudo_id.nil? ? "" : Conteudo.find(topicos_conteudo.conteudo_id).nome %></td>
                <td><%= topicos_conteudo.descricao %></td>
                <td><%= topicos_conteudo.objetivo %></td>
                <td><%= topicos_conteudo.resumo %></td>
                <!-- <td><%#= topicos_conteudo.formato_conteudo_id.nil? ? "" : FormatoConteudo.find(topicos_conteudo.formato_conteudo_id).nome %></td> -->
                <td><a href="<%= topicos_conteudo.link %>"><%= topicos_conteudo.link %></a></td>
                <td>
                  <div class="input-group-btn">
                    <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button">Ações <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Ver', topicos_conteudo, :title => 'Visualizar' %></li>
                      <li>
                        <%= link_to 'Editar', edit_topicos_conteudo_path(topicos_conteudo), :title => 'Editar' %>
                      </li>
                      <li>
                        <%= link_to 'Deletar', topicos_conteudo, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse registro ?' }, :title => 'Deletar' %>
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

app/views/topicos_conteudos/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title border-rsup">
					<div class="row">
						<div class="col-lg-1 col-sm-2 col-md-2 col-xs-2">
							<%=link_to '<i class="fa fa-reply"></i> Voltar'.html_safe,topicos_conteudos_path, :class => 'btn btn-white', :title => 'Voltar/Cancelar' %>
						</div>
						<div class="col-lg-11 col-sm-10 col-md-10 col-xs-10">
							<h2 align="center">Novo tópico de conteúdo</h2>
					</div>
				</div>
				<div class="ibox-content border-rinf">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/topicos_conteudos/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title border-rsup">
          <div class="row">
            <div class="col-lg-1 col-sm-2 col-md-2 col-xs-2">
             <%= link_to '<i class="fa fa-reply"></i> Voltar'.html_safe,topicos_conteudos_path, :class => 'btn btn-white', :title => 'Voltar' %>
            </div>
            <div class="col-lg-11 col-sm-10 col-md-10 col-xs-10">
              <h2 align="center">Visualizando conteúdo</h2> 
            </div>
          </div>
        </div>
        <div class="ibox-content border-rinf">
          <p id="notice">
            <center class="alert-info">
              <%= notice %> 
            </center>
          </p>
          <div class="panel panel-default">
            <div class="panel-body">
              <p>
                <strong>Conteúdo:</strong>
                <%= @topicos_conteudo.conteudo_id.nil? ? "" : Conteudo.find(@topicos_conteudo.conteudo_id).nome %>
              </p>
              <!-- <p>
                <strong>Formato conteudo:</strong>
                 <%#= @topicos_conteudo.formato_conteudo_id.nil? ? "" : FormatoConteudo.find(@topicos_conteudo.formato_conteudo_id).nome %>
              </p> -->
              <p>
                <strong>Descrição do tópico:</strong>
                <%= @topicos_conteudo.descricao %>
              </p>
              <p>
                <strong>Objetivo do tópico de conteúdo:</strong>
                <%= @topicos_conteudo.objetivo %>
              </p>
              <p>
                <strong>Resumo do tópico de conteúdo:</strong>
                <%= @topicos_conteudo.resumo %>
              </p>
              <p>
                <strong>Vídeo:</strong><br>
                <iframe width="700" height="700" src="<%= @topicos_conteudo.link.gsub('watch?v=','embed/')%>" frameborder="0" allowfullscreen></iframe>
              </p>

            </div>
          </div>
            <%= link_to '<i class="fa fa-edit"></i> Editar'.html_safe, edit_topicos_conteudo_path(@topicos_conteudo), :class => 'btn btn-white  ', :title => 'Editar' %>
            <%= link_to '<i class="fa fa-plus"></i> Novo'.html_safe, new_topicos_conteudo_path, :class => 'btn btn-white', :title => 'Novo' %>
        </div>
      </div>
    </div>
  </div>
</div>